### PR TITLE
add sub covers

### PR DESCRIPTION
**Pull request by ArrogantGao**
Added a new struct `SubCover` to store the covered item's id and the corresponding clause.
Added the algorithm to construct all possible sub-covers iteratively and corresponding tests.

### CODE REVIEW

**Comment by ArrogantGao** [comment]
I also force the unmasked bits of clause to be 0, which will make it easier to check are two clause are the same.

**Comment by ArrogantGao** [comment]
I added JuMP solver, by relaxing the set cover problem to a LP + random pick.
Not ready to be merged yet, I will work to support the truth table with multiple terms.

**Comment by ArrogantGao** [comment]
added support to truth with multiple terms.

**Comment by GiggleLiu** [comment]
Looks great!

**Pull request merged**
