### PR TITLE
Reduced alpha tensor with potential mis size

### PR DESCRIPTION
**Pull request by GiggleLiu**

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Documenter registry has some delay:
```julia
ERROR: Unsatisfiable requirements detected for package GenericTensorNetworks [3521c873]:
 GenericTensorNetworks [3521c873] log:
 ├─possible versions are: 1.0.0-2.1.0 or uninstalled
 └─restricted to versions 2.2.0-2 by TensorBranching [8[6](https://github.com/ArrogantGao/TensorBranching.jl/actions/runs/10011089788/job/27673750838?pr=13#step:5:7)172e9d] — no versions left
   └─TensorBranching [861[7](https://github.com/ArrogantGao/TensorBranching.jl/actions/runs/10011089788/job/27673750838?pr=13#step:5:8)2e9d] log:
     ├─possible versions are: 1.0.0 or uninstalled
     └─TensorBranching [[8](https://github.com/ArrogantGao/TensorBranching.jl/actions/runs/10011089788/job/27673750838?pr=13#step:5:9)6172e9d] is fixed to version 1.0.0-DEV
```

**Comment by ArrogantGao** [comment]
How the key word `potential` works?

**Comment by ArrogantGao** [comment]
> Documenter registry has some delay:
> 
> ```julia
> ERROR: Unsatisfiable requirements detected for package GenericTensorNetworks [3521c873]:
>  GenericTensorNetworks [3521c873] log:
>  ├─possible versions are: 1.0.0-2.1.0 or uninstalled
>  └─restricted to versions 2.2.0-2 by TensorBranching [8[6](https://github.com/ArrogantGao/TensorBranching.jl/actions/runs/10011089788/job/27673750838?pr=13#step:5:7)172e9d] — no versions left
>    └─TensorBranching [861[7](https://github.com/ArrogantGao/TensorBranching.jl/actions/runs/10011089788/job/27673750838?pr=13#step:5:8)2e9d] log:
>      ├─possible versions are: 1.0.0 or uninstalled
>      └─TensorBranching [[8](https://github.com/ArrogantGao/TensorBranching.jl/actions/runs/10011089788/job/27673750838?pr=13#step:5:9)6172e9d] is fixed to version 1.0.0-DEV
> ```

The documenter works offline now.

**Comment by ArrogantGao** [comment]
The documents have been updated, but still cannot be properly built.

**Comment by GiggleLiu** [comment]
The potential means the potential increase of environment MIS size, by setting a vertex is set to 0 comparing with 1.
It is usually set to degree(v) - those connected to inner vertices.

**Pull request merged**
